---
name: "Presidio client - execute analyze action"
description: "Github Action to execute Presidio framework using presidio_cli"
inputs:
  verify-path:
    description: Path to verify
    required: false
    default: "."
  configuration-file:
    description: Path to configuration file
    required: false
    default: "default"
  configuration-data:
    description: Simple configuration data directly
    required: false
    default: ""
  presidio-cli-version:
    description: Presidio cli version
    required: false
    default: "0.0.3"
# branding:
#  icon: 'arrow-down'
#  color: 'blue'
runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install presidio-cli
      uses: BSFishy/pip-action@v1
      with:
        packages: presidio-cli==${{ inputs.presidio-cli-version }}

    - name: Get branch names
      id: branch-names
      uses: tj-actions/branch-names@v5.1

    - name: Simple check 🥌
      run: |
        ls -alR .
        python -m presidio_cli --help
      shell: bash

    - name: Run presidio-cli with default configuration
      if: ${{ inputs.configuration-data }} == "" && ${{ inputs.configuration-file }} == "default"
      run: |
        python -m presidio_cli -c ${GITHUB_ACTION_PATH}/conf/default.yaml ${{ inputs.verify-path }}
      shell: bash

    - name: Run presidio-cli with configuration file
      if: ${{ inputs.configuration-data }} == "" && ${{ inputs.configuration-file }} != "default"
      run: |
        echo """env vars
            GITHUB_ACTION_PATH = ${GITHUB_ACTION_PATH}
            input params:
              configuration-file = ${{ inputs.configuration-file }}
              configuration-data = ${{ inputs.configuration-data }}
            """
        python -m presidio_cli -c ${{ inputs.configuration-file }} ${{ inputs.verify-path }}
      shell: bash

    - name: Run presidio-cli with configuration data
      if: ${{ inputs.configuration-data }} != ""
      run: |
        python -m presidio_cli -d ${{ inputs.configuration-data }} ${{ inputs.verify-path }}
      shell: bash
