---
name: "Presidio Action"
description: "Github Action to execute PII checks using the Presidio CLI"
branding:
  icon: 'alert-circle'
  color: 'yellow'
inputs:
  path:
    description: Path to verify
    required: false
    default: "."
  configuration-file:
    description: Path to custom configuration file
    required: false
    default: ""
  configuration-data:
    description: Configuration data as an inline YAML configuration
    required: false
    default: ""
  output:
    description: Format of output
    required: false
    default: "auto"
  publish:
    description: Publish result as a PR comment
    required: false
    default: "true"
  upload:
    description: Upload results as an artifact
    required: false
    default: "true"
  presidio-cli-version:
    description: Presidio CLI version
    required: false
    default: "latest"
  lang-models:
    description: List of additional language models to install
    required: false
    default: ""
  only-changed-files:
    description: Only run checks for changed files
    required: false
    default: true

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: cache 
      uses: actions/cache@v2
      with:
        path: |
          '~/.cache/pip'
          '~/.local/share/virtualenvs'
        key: ${{ runner.os }}-presidio-cli-${{ inputs.presidio-cli-version }}-main

    - name: Install presidio-cli
      run: |
        if [ "${{ inputs.presidio-cli-version }}" == "latest" ]
        then {
          pip install --upgrade presidio-cli
        } else {
          pip install presidio-cli==${{ inputs.presidio-cli-version }}
        }
        fi
      shell: bash

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v17

    - name: Install en language models
      run: |
        echo "install required models "
        # python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_lg
        echo "install additional models"
        while IFS= read -r lang_model
        do
          if [[ ! -z "${lang_model}" ]]; then
            python -m spacy download "${lang_model}"
          fi
        done <<< "${{ inputs.lang-models }}"
      shell: bash

    - name: Run presidio
      run: |
        CONFIG_OPTION=""
        
        if [ "${{ inputs.configuration-data }}" != "" ]
        then {
          CONFIG_OPTION="-d ${{ inputs.configuration-data }}"
        }
        fi

        if [ "${{ inputs.configuration-file }}" != "" ]
        then {
          CONFIG_OPTION="-c ${{ inputs.configuration-file }}"
        }
        fi

        if [ "${{ inputs.only-changed-files }}" == "true" ]
        then {
          for file in ${{ steps.changed-files.outputs.all_changed_files }}
          do {
            presidio \
              -f "${{ inputs.output }}" "${CONFIG_OPTION}" \
              $file | tee ./.presidio-output.txt
          }
          done
        } else {
          presidio \
            -f "${{ inputs.output }}" "${CONFIG_OPTION}" \
            "${{ inputs.path }}" | tee ./.presidio-output.txt
        }
        fi
      shell: bash
    
    - name: Beautify PR comment 🧨
      if: ${{ github.event_name == 'pull_request' && contains(inputs.publish, 'true') &&  contains(inputs.output, 'standard') }}
      run: |
        echo """
        ### PII Check
        """ | tee ./.presidio-output-comment.txt
        if [[ ! -s ./.presidio-output.txt ]]; then
          echo """
          Based on configuration Presidio does not found potential PII data
          """
        else
          echo """
          <details><summary>Presidio found potential PII data in the following files:</summary>
          <p>

          \`\`\`
          $(cat ./.presidio-output.txt)
          \`\`\`
          
          </p></details>

          """ | tee -a ./.presidio-output-comment.txt
        fi
      shell: bash

    - name: Publish warnings as comment to pull request
      if: ${{ github.event_name == 'pull_request' && contains(inputs.publish, 'true') &&  contains(inputs.output, 'standard') }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: "${{ inputs.path }}-${{ inputs.configuration-file }}-${{ inputs.output }}"
        path: "./.presidio-output-comment.txt"

    - name: Upload report 🔼
      if: ${{ github.event_name == 'pull_request' && contains(inputs.upload, 'true') }}
      uses: actions/upload-artifact@v2
      with:
        name: "PII output in format ${{ inputs.output }}"
        path: "./.presidio-output.txt"
